services:
  - type: web
    name: AngiBlog-Backend
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start

  - type: static
    name: AngiBlog-Frontend
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html